name: epay
description: "A new Flutter project."


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.3
  dio: ^5.9.2
  cached_network_image: ^3.4.1
  shared_preferences: ^2.5.5
  pinput: ^6.0.2
  flutter_svg: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_gen_runner:
  build_runner:


flutter:
  uses-material-design: true

  assets:
    - assets/splash/
    - assets/onboarding/
    - assets/auth/
    - assets/home/top_section/
    - assets/home/pay_bill/
    - assets/home/remittance/
    - assets/home/cash_out/
    - assets/home/add_money/
    - assets/home/send_money/